version: '5.0'

actions:
  generate_composite_datasets:
    run: ehrql:v1 python analysis/generate_composite.py
    outputs:
      highly_sensitive:
        datasets: output/composite/*.csv.gz
  
  analysis:
    run: python:v2 analysis/analysis.py
    needs: [generate_composite_datasets]
    outputs:
      highly_sensitive:
        analysis: output/analysis_results.csv
        