version: '5.0'

actions:
  generate_measures:
    run: ehrql:v1 generate-measures analysis/dataset_definition.py --output output/measures_attendances.csv.gz
    outputs:
      highly_sensitive:
        measures: output/measures_attendances.csv.gz

  analysis:
    run: python:v2 analysis/preprocess.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        analysis: output/preprocess_results.csv
        #analysis_summary: output/preprocess_summary.csv.gz