version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz
  
  analysis:
    run: python:v2 analysis/analysis.py
    outputs:
      highly_sensitive:
        analysis: output/analysis_results.csv
        